config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  # CRUD - CREATE, READ, UPDATE, DELETE
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Responsible for showing all pages.
  def index
    # if we want our view to have access to the var
    # we need an instance variable
    @pages = Page.all
    # render: index
  end

  # Showing a specific page.
  def show
    @page = Page.find(params[:id])
    # render: show - app/views/pags/show.html.erb
  end

  # Showing a form to edit an existing page.
  def edit
    @page = Page.find(params[:id])
    # render: edit - app/views/pages/edit.html.erb
  end

  # Responsible for showing a form to create a new page.
  def new
    @page = Page.new
    # render: new - app/views/pages/show.htmls.erb
  end

  # Responsible for saving a new record in our database.
  def create
    # Strong Params
    page = Page.new(page_params)
    # executes the sql to try to save the new page in the database
    if page.save
      # success - new record in the database
      redirect_to page_path(page)
    else
      # fail = failed to execute the sql for some reason
      render :new
    end
  end

  def destroy
    page = Page.find(params[:id])
    page.destroy
    redirect_to pages_path
  end

  def update
    @page = Page.find(params[:id])
    if @page.update(page_params)
      #success
      redirect_to page_path(@page)
    else
      #fail
      render :edit
    end
  end

  private
    def page_params
      params.require(:page).permit(:title, :author, :body, :private)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Pages', pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Editing: <%= @page.title %></h1>

<%= form_for @page do |f| %>
  <div>
    <%= f.text_field :title, placeholder: 'Title', required: true %>
    <%= f.label :title %>
  </div>

  <div>
    <%= f.text_field :author, placeholder: 'Author', required: true %>
    <%= f.label :author%>
  </div>

  <div>
    <%= f.text_area :body, placeholder: 'Body', required: true %>
    <%= f.label :body%>
  </div>

  <div>
    <%= f.check_box :private %>
    <%= f.label :private %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back to home', pages_path %>

app/views/pages/index.html.erb
<h1>Welcome to my blog</h1>
<h2>Check out all of my cool blog posts.</h2>
<%= link_to 'New Blog Post', new_page_path %>

<% @pages.each do |page| %>
  <div>
    <h3>
      <!-- <a href="/pages/<%= page.id %>"> <%= page.title %></a> -->
      <%= link_to page.title, page_path(page) %>
    </h3>
    <i>Author: <%= page. author %></i>
    <strong>PRIVATE: <%= page.private ? 'YES' : 'NO' %></strong>
    <%= link_to 'Delete', page_path(page), method: :delete %>
  </div>
  <hr>
<% end %>

<!-- NON ECHOING ERB TAG -->
<!-- loops, conditionals, variables -->
<% %>

<!-- ECHOING ERB TAG -->
<!-- print out the value of a variable -->
<%= %>

app/views/pages/new.html.erb
<h1>Create New Blog Post</h1>

<%= form_for @page do |f| %>
  <div>
    <%= f.text_field :title, placeholder: 'Title', required: true %>
    <%= f.label :title %>
  </div>

  <div>
    <%= f.text_field :author, placeholder: 'Author', required: true %>
    <%= f.label :author%>
  </div>

  <div>
    <%= f.text_area :body, placeholder: 'Body', required: true %>
    <%= f.label :body%>
  </div>

  <div>
    <%= f.check_box :private %>
    <%= f.label :private %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back to home', pages_path %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<hr>
<i>Author: <%= @page.author %></i>
<br>
<i>Created: <%= @page.created_at %></i>

<p><%= @page.body %></p>

<%= link_to 'Edit', edit_page_path(@page) %>
<%= link_to 'Back to home.', pages_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>